# Generated by Django 5.1.6 on 2025-03-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_rename_publication_book_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255)),
                ('flagged', models.BooleanField(default=False)),
            ],
        ),
    ]
